name: awx-command

on:
  repository_dispatch:
    types: [awx-command]

  workflow_dispatch:
    inputs:
      repository:
        description: 'The repository from which the slash command was dispatched'
        required: true
      comment-id:
        description: 'The comment-id of the slash command'
        required: true
      value1:
        description: 'The value1 of the slash command'
        required: false

jobs:
  awx:
    runs-on:
      - ubuntu-latest

    steps:
      - name: Set name output
        id: name
        run: |
          VALUE1=${{ github.event.inputs.value1 }}
          echo "::set-output name=value1::${VALUE1:-"Octocat"}"

      - name: Output command and arguments
        run: |
          echo ${{ github.event.inputs.repository }}
          echo ${{ github.event.inputs.comment-id }}
          echo ${{ github.event.inputs.test-data }}
          echo ${{ steps.name.outputs.value1 }}

      - name: Create URL to the run output
        id: vars
        run: echo ::set-output name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.DISPATCH_TEST_PAT }}
          repository: ${{ github.event.inputs.repository }}
          comment-id: ${{ github.event.inputs.comment-id }}
          body: |
            [Command run output][1]

            [1]: ${{ steps.vars.outputs.run-url }}
          reaction-type: hooray
