name: help-command
on:
  repository_dispatch:
    types: [help-command]

jobs:
  help:
    runs-on:
      - ubuntu-latest

    steps:
      - name: Update comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.DISPATCH_TEST_PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            > Command | Description | Product list | Examples
            > --- | --- | ---
            > /help | This output
            > /awx [\<args\> ...] | Echos back a list of arguments | product=all<br>product=fruits<br>product=apple<br>product=orange | /awx product=orange tags=tuned,prometheus limit=mons<br>/awx product=apple tags=node_exporter
          reaction-type: hooray
