name: slash-command-dispatch

on:
  issue_comment:
    types: [created]

jobs:
  slash-command-dispatch:
    runs-on:
      - ubuntu-latest

    steps:
      - name: Slash Command Dispatch
        id: scd
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.DISPATCH_TEST_PAT }}
          reaction-token: ${{ secrets.DISPATCH_TEST_PAT }}
          config: >
            [
              {
                "command": "help",
                "permission": "none",
                "issue_type": "pull-request",
                "dispatch_type": "repository"
              },
              {
                "command": "awx",
                "permission": "none",
                "issue_type": "pull-request",
                "dispatch_type": "workflow",
                "static_args": [
                  "repository=${{ github.repository }}",
                  "comment-id=${{ github.event.comment.id }}",
                  "comment-author=${{ github.event.comment.user.login }}",
                  "comment-body=${{ github.event.comment.body }}"
                ]
              }
            ]

      - name: Edit comment with error message
        if: failure()
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.DISPATCH_TEST_PAT }}
          repository: ${{ github.event.inputs.repository }}
          comment-id: ${{ github.event.comment.id }}
          body: |
            [Failed command run output][1]

            [1]: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          reaction-type: '-1'

      - name: Edit comment with error message
        if: steps.scd.outputs.error-message
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.DISPATCH_TEST_PAT }}
          repository: ${{ github.event.inputs.repository }}
          comment-id: ${{ github.event.comment.id }}
          body: |
            > ${{ steps.scd.outputs.error-message }}
          reactions: '-1'
