name: slash-command-dispatch

on:
  issue_comment:
    types: [created]

jobs:
  slash-command-dispatch:
    runs-on:
      - ubuntu-latest

    steps:
      - name: Slash Command Dispatch
        id: scd
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.DISPATCH_TEST_PAT }}
          config: >
            [
              {
                "command": "help",
                "issue_type": "pull-request",
                "dispatch_type": "repository"
              },
              {
                "command": "awx",
                "issue_type": "pull-request",
                "dispatch_type": "workflow",
                "static_args": [
                  "repository=${{ github.repository }}",
                  "comment-id=${{ github.event.comment.id }}"
                ]
              }
            ]

      - name: Create URL to the run output
        if: failure()
        id: vars
        run: echo ::set-output name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID

      - name: Edit comment with error message
        if: failure()
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.DISPATCH_TEST_PAT }}
          repository: ${{ github.event.inputs.repository }}
          comment-id: ${{ github.event.inputs.comment-id }}
          body: |
            [Command failed run output][1]

            [1]: ${{ steps.vars.outputs.run-url }}
          reaction-type: '-1'

      - name: Edit comment with error message
        if: steps.scd.outputs.error-message
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.DISPATCH_TEST_PAT }}
          repository: ${{ github.event.inputs.repository }}
          comment-id: ${{ github.event.comment.id }}
          body: |
            > ${{ steps.scd.outputs.error-message }}
          reactions: '-1'
